### ISSUE TITLE
rubigen 1.5.8

### ISSUE THREAD

**Issue by hollerbach** [drnic/install_theme#5]
Hello, Dr Nic. Is this gem suported? If so, I would like to report a small problem... 

best regards

install_theme -h

/Users/hollerbach/.rvm/gems/ruby-2.1.1/gems/rubigen-1.5.8/lib/rubigen/options.rb:31:in `default_options': undefined method`write_inheritable_attribute' for RubiGen::Base:Class (NoMethodError)
    from /Users/hollerbach/.rvm/gems/ruby-2.1.1/gems/rubigen-1.5.8/lib/rubigen/base.rb:84:in `<class:Base>'
    from /Users/hollerbach/.rvm/gems/ruby-2.1.1/gems/rubigen-1.5.8/lib/rubigen/base.rb:79:in`module:RubiGen'
    from /Users/hollerbach/.rvm/gems/ruby-2.1.1/gems/rubigen-1.5.8/lib/rubigen/base.rb:42:in `<top (required)>'
    from /Users/hollerbach/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /Users/hollerbach/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/hollerbach/.rvm/gems/ruby-2.1.1/gems/rubigen-1.5.8/lib/rubigen.rb:6:in`<top (required)>'
    from /Users/hollerbach/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/hollerbach/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /Users/hollerbach/.rvm/gems/ruby-2.1.1@global/gems/install_theme-0.8.2/lib/install_theme.rb:4:in `<top (required)>'
    from /Users/hollerbach/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /Users/hollerbach/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/hollerbach/.rvm/gems/ruby-2.1.1@global/gems/install_theme-0.8.2/bin/install_theme:7:in`<top (required)>'
    from /Users/hollerbach/.rvm/rubies/ruby-2.1.1/bin/install_theme:23:in `load'
    from /Users/hollerbach/.rvm/rubies/ruby-2.1.1/bin/install_theme:23:in`<main>'
    from /Users/hollerbach/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
    from /Users/hollerbach/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in`<main>'

**Comment by PeteBoucher** [comment]
Same issue here, using:
`ruby-2.1.2`
`Rails 4.1.4`

**Comment by andrew-carroll** [comment]
Edit: On further inspection, install_theme breaks rails (versions below) altogether. The same error is given when trying to run the server.

---

Similar issue here, but the error is referencing rubigen 1.5.7 for me.
`ruby-2.1.5`
`Rails 4.1.8`

**Output**
install_theme -h
/home/andrew/.rvm/gems/ruby-2.1.5/gems/rubigen-1.5.7/lib/rubigen/options.rb:31:in `default_options': undefined method`write_inheritable_attribute' for RubiGen::Base:Class (NoMethodError)
  from /home/andrew/.rvm/gems/ruby-2.1.5/gems/rubigen-1.5.7/lib/rubigen/base.rb:84:in `<class:Base>'
  from /home/andrew/.rvm/gems/ruby-2.1.5/gems/rubigen-1.5.7/lib/rubigen/base.rb:79:in`module:RubiGen'
  from /home/andrew/.rvm/gems/ruby-2.1.5/gems/rubigen-1.5.7/lib/rubigen/base.rb:42:in `<top (required)>'
  from /home/andrew/.rvm/gems/ruby-2.1.5/gems/rubigen-1.5.7/lib/rubigen.rb:10:in`require'
  from /home/andrew/.rvm/gems/ruby-2.1.5/gems/rubigen-1.5.7/lib/rubigen.rb:10:in `<top (required)>'
  from /home/andrew/.rvm/gems/ruby-2.1.5/gems/install_theme-0.8.2/lib/install_theme.rb:4:in`require'
  from /home/andrew/.rvm/gems/ruby-2.1.5/gems/install_theme-0.8.2/lib/install_theme.rb:4:in `<top (required)>'
  from /home/andrew/.rvm/gems/ruby-2.1.5/gems/install_theme-0.8.2/bin/install_theme:7:in`require'
  from /home/andrew/.rvm/gems/ruby-2.1.5/gems/install_theme-0.8.2/bin/install_theme:7:in `<top (required)>'
  from /home/andrew/.rvm/gems/ruby-2.1.5/bin/install_theme:23:in`load'
  from /home/andrew/.rvm/gems/ruby-2.1.5/bin/install_theme:23:in `<main>'
  from /home/andrew/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in`eval'
  from /home/andrew/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'

**Comment by besi** [comment]
Same issue here, using:

```
ruby-2.1.2 
rails 4.2.6
```
